stages:
  - build
  - test
  - push

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:20.10.7-dind

before_script:
  - docker info
  - apk add --no-cache bash

build:
  stage: build
  image: golang:1.20-alpine
  script:
    - apk add --no-cache git
    - go mod download
    - go build -o main .
    - docker build -t my-go-app .

test:
  stage: test
  image: golang:1.20-alpine
  services:
    - name: postgres:13
      alias: postgres
  variables:
    POSTGRES_DB: userdb
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    DATABASE_URL: postgres://user:password@postgres:5432/userdb?sslmode=disable
  script:
    - apk add --no-cache git
    - go mod download
    - go test -v -coverprofile=coverage.out ./...
    - go tool cover -func=coverage.out
